from vla.config import (
    ACTION_DIM, ACTION_TOKEN, CHUNK_SIZE, GRIPPER_LOSS_WEIGHT,
    MAX_LENGTH, MODEL_REGISTRY, NORM_ACTION, NORM_MAX, NORM_MIN,
    RGB_PAD, SYSTEM_PROMPT,
)
from vla.model import VLA
